import Config

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :pki_ra_portal, PkiRaPortalWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "h1rG0cHLuRUGnrih4htqeIHL/aY1r8PGIj/E+7Pn1a7aPKT1OoO1oQkhlp5qsshq",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:pki_ra_portal, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:pki_ra_portal, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :pki_ra_portal, PkiRaPortalWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$",
      # Gettext translations
      ~r"priv/gettext/.*\.po$",
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/pki_ra_portal_web/router\.ex$",
      ~r"lib/pki_ra_portal_web/(controllers|live|components)/.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :pki_ra_portal, dev_routes: true

# PlatformRepo — pki_platform_engine dependency needs its DB configured
config :pki_platform_engine, PkiPlatformEngine.PlatformRepo,
  username: "postgres",
  password: System.get_env("POSTGRES_PASSWORD", "postgres"),
  hostname: "localhost",
  port: String.to_integer(System.get_env("POSTGRES_PORT", "5432")),
  database: "pki_platform_dev",
  pool_size: 3

config :pki_platform_engine, PkiPlatformEngine.TenantRepo,
  hostname: "localhost",
  port: String.to_integer(System.get_env("POSTGRES_PORT", "5432")),
  username: "postgres",
  password: System.get_env("POSTGRES_PASSWORD", "postgres"),
  pool_size: 2

# RA Engine client for local dev — Direct calls engine modules in-process (no HTTP)
# Switch to PkiRaPortal.RaEngineClient.Http for remote/separate deployment
config :pki_ra_portal,
  ra_engine_client: PkiRaPortal.RaEngineClient.Direct,
  ra_engine_url: System.get_env("RA_ENGINE_URL", "http://localhost:4003"),
  internal_api_secret: System.get_env("INTERNAL_API_SECRET", "dev-secret"),
  cookie_secure: false

# RA Engine + CA Engine database config (needed when running Direct mode in-process)
config :pki_ra_engine, PkiRaEngine.Repo,
  username: "postgres",
  password: System.get_env("POSTGRES_PASSWORD", "postgres"),
  hostname: "localhost",
  port: String.to_integer(System.get_env("POSTGRES_PORT", "5432")),
  database: "pki_ra_engine_dev",
  pool_size: 5

config :pki_ca_engine, PkiCaEngine.Repo,
  username: "postgres",
  password: System.get_env("POSTGRES_PASSWORD", "postgres"),
  hostname: "localhost",
  port: String.to_integer(System.get_env("POSTGRES_PORT", "5432")),
  database: "pki_ca_engine_dev",
  pool_size: 2

config :pki_audit_trail, PkiAuditTrail.Repo,
  username: "postgres",
  password: System.get_env("POSTGRES_PASSWORD", "postgres"),
  hostname: "localhost",
  port: String.to_integer(System.get_env("POSTGRES_PORT", "5432")),
  database: "pki_ca_engine_dev",
  pool_size: 2

# Disable engine HTTP servers (portal runs Direct, not HTTP)
config :pki_ra_engine, start_http: false
config :pki_ca_engine, :start_http, false

# Hammer rate limiter config (pulled in via engine dependencies)
config :hammer,
  backend: {Hammer.Backend.ETS, [expiry_ms: 60_000 * 60 * 2, cleanup_interval_ms: 60_000 * 10]}

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true
