#!/usr/bin/env bash
# deploy/generate-env.sh — Generate /opt/pki/.env with cryptographic secrets
#
# Run on the server after install.sh:
#   sudo bash deploy/generate-env.sh
#   sudo bash deploy/generate-env.sh --interactive   # prompt for hostnames & admin password
#
# All passwords, salts, and keys are generated using openssl rand.
# The admin password is hashed with argon2 (installed by install.sh).
#
# Safe to re-run: will NOT overwrite an existing .env unless --force is passed.

set -euo pipefail

ENV_FILE="/opt/pki/.env"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'
info()  { echo -e "${GREEN}[env]${NC} $*"; }
warn()  { echo -e "${YELLOW}[env]${NC} $*"; }
die()   { echo -e "${RED}[env] ERROR:${NC} $*" >&2; exit 1; }

# ── Parse arguments ──────────────────────────────────────────────────────────
INTERACTIVE=false
FORCE=false
for arg in "$@"; do
  case "$arg" in
    --interactive|-i) INTERACTIVE=true ;;
    --force|-f)       FORCE=true ;;
    *)                warn "Unknown argument: $arg" ;;
  esac
done

[[ $EUID -eq 0 ]] || die "Run as root: sudo bash deploy/generate-env.sh"

if [[ -f "$ENV_FILE" && "$FORCE" != true ]]; then
  die "$ENV_FILE already exists. Use --force to overwrite, or edit it manually."
fi

# ── Helpers ──────────────────────────────────────────────────────────────────
# URL-safe base64: no +, /, or = (safe for unquoted shell .env values)
rand_base64()  { openssl rand -base64 "$1" 2>/dev/null | tr '+/' '-_' | tr -d '=\n'; }
rand_hex()     { openssl rand -hex "$1" 2>/dev/null | tr -d '\n'; }
rand_password(){ openssl rand -base64 18 2>/dev/null | tr '+/' '-_' | tr -d '=\n'; }

prompt_or_default() {
  local var_name="$1" default="$2" prompt_text="$3"
  if $INTERACTIVE; then
    read -rp "$(echo -e "${CYAN}$prompt_text${NC} [$default]: ")" value
    echo "${value:-$default}"
  else
    echo "$default"
  fi
}

prompt_password() {
  local prompt_text="$1" default="$2"
  if $INTERACTIVE; then
    read -rsp "$(echo -e "${CYAN}$prompt_text${NC}: ")" value
    echo ""  # newline after hidden input
    echo "${value:-$default}"
  else
    echo "$default"
  fi
}

# ── Generate all secrets ─────────────────────────────────────────────────────
info "Generating cryptographic secrets..."

POSTGRES_PASSWORD=$(rand_password)
SECRET_KEY_BASE=$(rand_base64 64)
INTERNAL_API_SECRET=$(rand_base64 32)

# Session salts (signing + encryption)
CA_PORTAL_SIGNING_SALT=$(rand_base64 16)
RA_PORTAL_SIGNING_SALT=$(rand_base64 16)
PLATFORM_SIGNING_SALT=$(rand_base64 16)
CA_PORTAL_ENCRYPTION_SALT=$(rand_base64 16)
RA_PORTAL_ENCRYPTION_SALT=$(rand_base64 16)
PLATFORM_ENCRYPTION_SALT=$(rand_base64 16)

# SoftHSM2 PINs
SOFTHSM_SO_PIN=$(rand_hex 4)
SOFTHSM_USER_PIN=$(rand_hex 4)

# ── Interactive prompts (or defaults) ────────────────────────────────────────
CA_PORTAL_HOST=$(prompt_or_default CA_PORTAL_HOST "ca.straptrust.com" "CA Portal hostname")
RA_PORTAL_HOST=$(prompt_or_default RA_PORTAL_HOST "ra.straptrust.com" "RA Portal hostname")
PLATFORM_HOST=$(prompt_or_default PLATFORM_HOST "admin.straptrust.com" "Platform Portal hostname")
CADDY_ACME_EMAIL=$(prompt_or_default CADDY_ACME_EMAIL "amirrudin.yahaya@gmail.com" "ACME email for TLS certs")
PLATFORM_ADMIN_USERNAME=$(prompt_or_default PLATFORM_ADMIN_USERNAME "trust_admin" "Platform admin username")
RESEND_API_KEY=$(prompt_or_default RESEND_API_KEY "CHANGE_ME" "Resend API key (or CHANGE_ME to set later)")
MAILER_FROM=$(prompt_or_default MAILER_FROM "PQC PKI Platform <noreply@${CA_PORTAL_HOST%%.*}.${CA_PORTAL_HOST#*.}>" "Mailer from address")

# Admin password — generate or prompt
ADMIN_PASSWORD=$(prompt_password "Platform admin password (leave blank to auto-generate)" "")
if [[ -z "$ADMIN_PASSWORD" ]]; then
  ADMIN_PASSWORD=$(rand_password)
  info "Generated admin password (shown once, save it!):"
  echo -e "  ${CYAN}${ADMIN_PASSWORD}${NC}"
fi

# Hash the password with argon2
if command -v argon2 &>/dev/null; then
  ARGON2_SALT=$(rand_hex 8)
  PLATFORM_ADMIN_PASSWORD_HASH=$(echo -n "$ADMIN_PASSWORD" | argon2 "$ARGON2_SALT" -id -t 3 -m 16 -p 4 -l 32 -e)
  info "Admin password hashed with argon2"
else
  warn "argon2 CLI not found — storing placeholder hash. Hash it after first deploy:"
  warn "  /opt/pki/releases/portals/bin/pki_portals eval 'IO.puts Argon2.hash_pwd_salt(\"your_password\")'"
  PLATFORM_ADMIN_PASSWORD_HASH="CHANGE_ME"
fi

# ── Write the .env file ─────────────────────────────────────────────────────
info "Writing ${ENV_FILE}..."

cat > "$ENV_FILE" << ENVFILE
# PKI CA System — Production Environment
# Generated by deploy/generate-env.sh on $(date -u +"%Y-%m-%d %H:%M:%S UTC")
# Direct BEAM deployment, no containers

# ── PostgreSQL ───────────────────────────────────────────────────────────────
POSTGRES_USER=postgres
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

# ── Shared secrets ───────────────────────────────────────────────────────────
SECRET_KEY_BASE=${SECRET_KEY_BASE}
INTERNAL_API_SECRET=${INTERNAL_API_SECRET}

# ── Platform admin ───────────────────────────────────────────────────────────
PLATFORM_ADMIN_USERNAME=${PLATFORM_ADMIN_USERNAME}
PLATFORM_ADMIN_PASSWORD_HASH=PLACEHOLDER_HASH

# ── Portal hostnames ─────────────────────────────────────────────────────────
CA_PORTAL_HOST=${CA_PORTAL_HOST}
RA_PORTAL_HOST=${RA_PORTAL_HOST}
PLATFORM_HOST=${PLATFORM_HOST}

# ── Email (Resend) ───────────────────────────────────────────────────────────
RESEND_API_KEY=${RESEND_API_KEY}
MAILER_FROM="${MAILER_FROM}"

# ── Caddy ACME ───────────────────────────────────────────────────────────────
CADDY_ACME_EMAIL=${CADDY_ACME_EMAIL}

# ── Session signing & encryption salts (set at build time — see build.sh) ────
CA_PORTAL_SIGNING_SALT=${CA_PORTAL_SIGNING_SALT}
RA_PORTAL_SIGNING_SALT=${RA_PORTAL_SIGNING_SALT}
PLATFORM_SIGNING_SALT=${PLATFORM_SIGNING_SALT}
CA_PORTAL_ENCRYPTION_SALT=${CA_PORTAL_ENCRYPTION_SALT}
RA_PORTAL_ENCRYPTION_SALT=${RA_PORTAL_ENCRYPTION_SALT}
PLATFORM_ENCRYPTION_SALT=${PLATFORM_ENCRYPTION_SALT}

# ── SoftHSM2 (system install) ────────────────────────────────────────────────
SOFTHSM_TOKEN_LABEL=PkiCA
SOFTHSM_SO_PIN=${SOFTHSM_SO_PIN}
SOFTHSM_USER_PIN=${SOFTHSM_USER_PIN}
PKCS11_LIB_PATH=/usr/lib/softhsm/libsofthsm2.so
HSM_SLOT=0
HSM_TOKEN_LABEL=PkiCA
SOFTHSM2_CONF=/etc/softhsm2.conf

# ── Service ports ────────────────────────────────────────────────────────────
CA_ENGINE_PORT=4001
RA_ENGINE_PORT=4003
CA_PORTAL_PORT=4002
RA_PORTAL_PORT=4004
PLATFORM_PORTAL_PORT=4006
VALIDATION_PORT=4005

# ── Public portal URLs (used in emails, links) ──────────────────────────────
CA_PORTAL_URL=https://${CA_PORTAL_HOST}
RA_PORTAL_URL=https://${RA_PORTAL_HOST}
PLATFORM_PORTAL_URL=https://${PLATFORM_HOST}

# ── Internal service URLs (localhost — no containers) ────────────────────────
CA_ENGINE_URL=http://127.0.0.1:4001
RA_ENGINE_URL=http://127.0.0.1:4003
VALIDATION_URL=http://127.0.0.1:4005

# ── Database URLs (PostgreSQL on localhost:5432) ─────────────────────────────
DATABASE_URL=ecto://postgres:${POSTGRES_PASSWORD}@localhost:5432/pki_ca_engine
CA_ENGINE_DATABASE_URL=ecto://postgres:${POSTGRES_PASSWORD}@localhost:5432/pki_ca_engine
RA_ENGINE_DATABASE_URL=ecto://postgres:${POSTGRES_PASSWORD}@localhost:5432/pki_ra_engine
VALIDATION_DATABASE_URL=ecto://postgres:${POSTGRES_PASSWORD}@localhost:5432/pki_validation
PLATFORM_DATABASE_URL=ecto://postgres:${POSTGRES_PASSWORD}@localhost:5432/pki_platform
AUDIT_TRAIL_DATABASE_URL=ecto://postgres:${POSTGRES_PASSWORD}@localhost:5432/pki_audit_trail

# ── Connection pool sizes ────────────────────────────────────────────────
# Total connections across 2 BEAM nodes must stay under PostgreSQL max_connections (300).
# Engines node: POOL_SIZE(10) x 2 repos + PLATFORM_POOL_SIZE(5) + AUDIT_POOL_SIZE(5) + VALIDATION_POOL_SIZE(15) = 45
# Portals node: same repos loaded in direct mode = 45
# Total: ~90 active + headroom for tenant dynamic repos
POOL_SIZE=10
PLATFORM_POOL_SIZE=5
AUDIT_POOL_SIZE=5
VALIDATION_POOL_SIZE=15
ENVFILE

# Inject argon2 hash safely (contains $ signs that break heredoc and bash source)
# Wrap in single quotes so `source .env` doesn't expand $argon2id, $v, $m etc.
PKI_HASH="$PLATFORM_ADMIN_PASSWORD_HASH" perl -pi -e "s/PLACEHOLDER_HASH/'\$ENV{PKI_HASH}'/" "$ENV_FILE"

# ── Set permissions ──────────────────────────────────────────────────────────
chown pki:pki "$ENV_FILE"
chmod 600 "$ENV_FILE"

echo ""
info "Environment file generated: ${ENV_FILE}"
info "Permissions: pki:pki 600"
echo ""
echo -e "${YELLOW}Review it before deploying:${NC}"
echo "  sudo cat $ENV_FILE"
echo ""
if [[ "$RESEND_API_KEY" == "CHANGE_ME" ]]; then
  echo -e "${YELLOW}Reminder:${NC} RESEND_API_KEY still needs to be set manually"
fi
if [[ "$PLATFORM_ADMIN_PASSWORD_HASH" == "CHANGE_ME" ]]; then
  echo -e "${YELLOW}Reminder:${NC} PLATFORM_ADMIN_PASSWORD_HASH still needs to be hashed"
fi
