#!/usr/bin/env bash
# deploy/secure-vps.sh — Harden a fresh Ubuntu VPS for PKI CA deployment
#
# Run as root on a fresh server BEFORE install.sh:
#   sudo bash deploy/secure-vps.sh
#   sudo bash deploy/secure-vps.sh --ssh-port 2222   # custom SSH port
#
# What this does:
#   1. System updates + unattended security upgrades
#   2. UFW firewall (SSH, HTTP, HTTPS only)
#   3. SSH hardening (key-only auth, no root login)
#   4. Fail2ban for brute-force protection
#   5. Kernel/network sysctl hardening
#   6. PostgreSQL locked to localhost
#   7. Shared memory and /tmp hardening
#   8. Automatic security updates
#
# Safe to re-run — all steps are idempotent.

set -euo pipefail

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
info()  { echo -e "${GREEN}[secure]${NC} $*"; }
warn()  { echo -e "${YELLOW}[secure]${NC} $*"; }
die()   { echo -e "${RED}[secure] ERROR:${NC} $*" >&2; exit 1; }

[[ $EUID -eq 0 ]] || die "Run as root: sudo bash deploy/secure-vps.sh"

# ── Parse arguments ──────────────────────────────────────────────────────────
SSH_PORT="${SSH_PORT:-22}"
for arg in "$@"; do
  case "$arg" in
    --ssh-port=*) SSH_PORT="${arg#*=}" ;;
    --ssh-port)   shift; SSH_PORT="${2:-22}" ;;
  esac
done

echo ""
info "=== VPS Security Hardening ==="
info "SSH port: $SSH_PORT"
echo ""

# ── 1. System updates ───────────────────────────────────────────────────────
info "1/8 Updating system packages..."
apt-get update -qq
DEBIAN_FRONTEND=noninteractive apt-get upgrade -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold"
info "  System packages updated"

# ── 2. Install security packages ────────────────────────────────────────────
info "2/8 Installing security packages..."
apt-get install -y --no-install-recommends \
  ufw \
  fail2ban \
  unattended-upgrades \
  apt-listchanges \
  logwatch \
  rkhunter

# ── 3. UFW Firewall ─────────────────────────────────────────────────────────
info "3/8 Configuring UFW firewall..."

# Reset to defaults (idempotent)
ufw --force reset >/dev/null 2>&1

# Default deny incoming, allow outgoing
ufw default deny incoming
ufw default allow outgoing

# Allow SSH (custom port if set)
ufw allow "$SSH_PORT/tcp" comment "SSH"

# Allow HTTP/HTTPS for Caddy + Let's Encrypt ACME
ufw allow 80/tcp comment "HTTP (Caddy/ACME)"
ufw allow 443/tcp comment "HTTPS (Caddy)"

# Enable (--force skips the confirmation prompt)
ufw --force enable
info "  UFW enabled — allowed: SSH(:$SSH_PORT), HTTP(:80), HTTPS(:443)"

# ── 4. SSH hardening ────────────────────────────────────────────────────────
info "4/8 Hardening SSH configuration..."

SSHD_CONFIG="/etc/ssh/sshd_config"
SSHD_HARDENING="/etc/ssh/sshd_config.d/99-pki-hardening.conf"

# Write hardening config as a drop-in (doesn't touch the main file)
cat > "$SSHD_HARDENING" << EOF
# PKI VPS SSH hardening — generated by deploy/secure-vps.sh
Port $SSH_PORT
PermitRootLogin no
PasswordAuthentication no
KbdInteractiveAuthentication no
ChallengeResponseAuthentication no
UsePAM yes
X11Forwarding no
AllowTcpForwarding no
ClientAliveInterval 300
ClientAliveCountMax 2
MaxAuthTries 3
MaxSessions 3
LoginGraceTime 30
EOF

# Ensure Include directive exists in main sshd_config
if ! grep -q "^Include /etc/ssh/sshd_config.d" "$SSHD_CONFIG" 2>/dev/null; then
  echo "Include /etc/ssh/sshd_config.d/*.conf" >> "$SSHD_CONFIG"
fi

# Validate config before restarting
if sshd -t 2>/dev/null; then
  systemctl restart sshd
  info "  SSH hardened: port=$SSH_PORT, root=no, password=no, key-only"
else
  rm -f "$SSHD_HARDENING"
  warn "  SSH config invalid — reverted hardening. Check manually."
fi

# ── 5. Fail2ban ─────────────────────────────────────────────────────────────
info "5/8 Configuring Fail2ban..."

cat > /etc/fail2ban/jail.local << EOF
# PKI VPS Fail2ban — generated by deploy/secure-vps.sh
[DEFAULT]
bantime  = 3600
findtime = 600
maxretry = 3
backend  = systemd

[sshd]
enabled  = true
port     = $SSH_PORT
filter   = sshd
logpath  = %(sshd_log)s
maxretry = 3
bantime  = 3600
EOF

systemctl enable fail2ban
systemctl restart fail2ban
info "  Fail2ban enabled: 3 strikes → 1 hour ban"

# ── 6. Kernel/network sysctl hardening ──────────────────────────────────────
info "6/8 Applying kernel/network hardening..."

cat > /etc/sysctl.d/99-pki-hardening.conf << 'EOF'
# PKI VPS sysctl hardening — generated by deploy/secure-vps.sh

# ── Network hardening ────────────────────────────────────────────────────────
# Prevent IP spoofing
net.ipv4.conf.all.rp_filter = 1
net.ipv4.conf.default.rp_filter = 1

# Ignore ICMP redirects (prevent MITM)
net.ipv4.conf.all.accept_redirects = 0
net.ipv4.conf.default.accept_redirects = 0
net.ipv4.conf.all.send_redirects = 0
net.ipv4.conf.default.send_redirects = 0
net.ipv6.conf.all.accept_redirects = 0
net.ipv6.conf.default.accept_redirects = 0

# Ignore source-routed packets
net.ipv4.conf.all.accept_source_route = 0
net.ipv4.conf.default.accept_source_route = 0
net.ipv6.conf.all.accept_source_route = 0
net.ipv6.conf.default.accept_source_route = 0

# SYN flood protection
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_max_syn_backlog = 2048
net.ipv4.tcp_synack_retries = 2

# Ignore ICMP broadcast pings
net.ipv4.icmp_echo_ignore_broadcasts = 1

# Log martian packets (impossible source addresses)
net.ipv4.conf.all.log_martians = 1
net.ipv4.conf.default.log_martians = 1

# Disable IPv4 forwarding (not a router)
net.ipv4.ip_forward = 0
net.ipv6.conf.all.forwarding = 0

# ── Kernel hardening ────────────────────────────────────────────────────────
# Restrict dmesg to root
kernel.dmesg_restrict = 1

# Restrict kernel pointer access
kernel.kptr_restrict = 2

# Restrict ptrace (prevents process snooping)
kernel.yama.ptrace_scope = 2

# Randomize memory layout (ASLR)
kernel.randomize_va_space = 2

# Restrict unprivileged BPF
kernel.unprivileged_bpf_disabled = 1

# ── File system hardening ───────────────────────────────────────────────────
# Prevent hard/symlink attacks
fs.protected_hardlinks = 1
fs.protected_symlinks = 1
fs.protected_fifos = 2
fs.protected_regular = 2
EOF

sysctl --system >/dev/null 2>&1
info "  Kernel/network hardening applied"

# ── 7. Shared memory hardening ──────────────────────────────────────────────
info "7/8 Hardening shared memory..."

# Restrict /dev/shm (prevent executable code in shared memory)
if ! grep -q '/dev/shm' /etc/fstab 2>/dev/null; then
  echo "tmpfs /dev/shm tmpfs defaults,noexec,nosuid,nodev 0 0" >> /etc/fstab
  mount -o remount /dev/shm 2>/dev/null || true
  info "  /dev/shm mounted noexec,nosuid,nodev"
else
  info "  /dev/shm already in fstab, skipping"
fi

# ── 8. Automatic security updates ───────────────────────────────────────────
info "8/8 Enabling automatic security updates..."

cat > /etc/apt/apt.conf.d/50unattended-upgrades << 'EOF'
Unattended-Upgrade::Allowed-Origins {
    "${distro_id}:${distro_codename}-security";
    "${distro_id}ESMApps:${distro_codename}-apps-security";
    "${distro_id}ESM:${distro_codename}-infra-security";
};
Unattended-Upgrade::Package-Blacklist {
    // Don't auto-upgrade BEAM/Erlang/PostgreSQL — we manage these manually
    "erlang";
    "postgresql";
    "elixir";
};
Unattended-Upgrade::AutoFixInterruptedDpkg "true";
Unattended-Upgrade::MinimalSteps "true";
Unattended-Upgrade::Remove-Unused-Kernel-Packages "true";
Unattended-Upgrade::Remove-Unused-Dependencies "true";
Unattended-Upgrade::Automatic-Reboot "false";
Unattended-Upgrade::Mail "";
EOF

cat > /etc/apt/apt.conf.d/20auto-upgrades << 'EOF'
APT::Periodic::Update-Package-Lists "1";
APT::Periodic::Unattended-Upgrade "1";
APT::Periodic::AutocleanInterval "7";
EOF

systemctl enable unattended-upgrades
info "  Auto security updates enabled (Erlang/PostgreSQL excluded)"

# ── Summary ──────────────────────────────────────────────────────────────────
echo ""
info "=== VPS Hardening Complete ==="
echo ""
echo -e "  ${GREEN}Firewall:${NC}     UFW active (SSH:$SSH_PORT, HTTP:80, HTTPS:443)"
echo -e "  ${GREEN}SSH:${NC}          Key-only, no root, port $SSH_PORT"
echo -e "  ${GREEN}Fail2ban:${NC}     3 failures → 1hr ban"
echo -e "  ${GREEN}Kernel:${NC}       ASLR, SYN protection, no forwarding, no redirects"
echo -e "  ${GREEN}Auto-update:${NC}  Security patches applied nightly"
echo ""

if [[ "$SSH_PORT" != "22" ]]; then
  echo -e "${YELLOW}IMPORTANT:${NC} SSH port changed to $SSH_PORT"
  echo -e "  Reconnect with: ssh -p $SSH_PORT user@server"
  echo ""
fi

echo -e "${YELLOW}BEFORE DISCONNECTING:${NC}"
echo "  1. Verify you can SSH in from another terminal"
echo "  2. Ensure your SSH public key is in ~/.ssh/authorized_keys"
echo "  3. If locked out, use VPS provider's console access"
echo ""
echo "Next: sudo bash deploy/install.sh"
