#!/usr/bin/env bash
# setup-softhsm-test.sh — Initialise a SoftHSM2 token and generate test keys
# for local BYOK-HSM integration testing.
#
# Usage:
#   ./scripts/setup-softhsm-test.sh
#
# Requirements:
#   - softhsm2-util (brew install softhsm / apt-get install softhsm2)
#   - pkcs11-tool  (brew install opensc / apt-get install opensc)

set -euo pipefail

# ---------------------------------------------------------------------------
# Colour helpers
# ---------------------------------------------------------------------------
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
info()  { echo -e "${GREEN}[INFO]${NC}  $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error() { echo -e "${RED}[ERROR]${NC} $*" >&2; exit 1; }

# ---------------------------------------------------------------------------
# 1. Check prerequisites
# ---------------------------------------------------------------------------
info "Checking prerequisites..."

command -v softhsm2-util >/dev/null 2>&1 || error "softhsm2-util not found. Install with: brew install softhsm  OR  apt-get install softhsm2"
command -v pkcs11-tool   >/dev/null 2>&1 || error "pkcs11-tool not found. Install with: brew install opensc  OR  apt-get install opensc"

SOFTHSM_VERSION=$(softhsm2-util --version 2>&1 | head -1)
info "SoftHSM2: ${SOFTHSM_VERSION}"

# ---------------------------------------------------------------------------
# 2. Detect OS and library path
# ---------------------------------------------------------------------------
UNAME=$(uname -s)
if [[ "${UNAME}" == "Darwin" ]]; then
  OS="mac"
  BREW_PREFIX=$(brew --prefix 2>/dev/null || echo "/opt/homebrew")
  # Homebrew arm64 default; fall back to Intel path
  if [[ -f "${BREW_PREFIX}/lib/softhsm/libsofthsm2.so" ]]; then
    LIB_PATH="${BREW_PREFIX}/lib/softhsm/libsofthsm2.so"
  elif [[ -f "/usr/local/lib/softhsm/libsofthsm2.so" ]]; then
    LIB_PATH="/usr/local/lib/softhsm/libsofthsm2.so"
  else
    error "libsofthsm2.so not found under Homebrew prefix (${BREW_PREFIX}). Did 'brew install softhsm' succeed?"
  fi
else
  OS="linux"
  if [[ -f "/usr/lib/softhsm/libsofthsm2.so" ]]; then
    LIB_PATH="/usr/lib/softhsm/libsofthsm2.so"
  elif [[ -f "/usr/lib/x86_64-linux-gnu/softhsm/libsofthsm2.so" ]]; then
    LIB_PATH="/usr/lib/x86_64-linux-gnu/softhsm/libsofthsm2.so"
  else
    error "libsofthsm2.so not found. Install with: apt-get install softhsm2"
  fi
fi
info "OS: ${OS} — PKCS#11 library: ${LIB_PATH}"

# ---------------------------------------------------------------------------
# 3. Set up SoftHSM2 config and token directory
# ---------------------------------------------------------------------------
TOKEN_DIR="${TMPDIR:-/tmp}/pki-softhsm-tokens"
rm -rf "${TOKEN_DIR}"
mkdir -p "${TOKEN_DIR}"

SOFTHSM2_CONF="${TOKEN_DIR}/softhsm2.conf"
cat > "${SOFTHSM2_CONF}" <<EOF
# SoftHSM2 config — generated by setup-softhsm-test.sh
directories.tokendir = ${TOKEN_DIR}
objectstore.backend = file
log.level = INFO
slots.removable = false
EOF

export SOFTHSM2_CONF
info "SoftHSM2 config written to: ${SOFTHSM2_CONF}"

# ---------------------------------------------------------------------------
# 4. Initialise token
# ---------------------------------------------------------------------------
LABEL="pki-test"
USER_PIN="1234"
SO_PIN="12345678"

info "Initialising SoftHSM2 token (label: ${LABEL}, slot: 0)..."
softhsm2-util --init-token --slot 0 \
  --label "${LABEL}" \
  --pin "${USER_PIN}" \
  --so-pin "${SO_PIN}"

# After init-token, SoftHSM2 reassigns slots. Re-read to find the one with our label.
SLOT_ID=$(softhsm2-util --show-slots 2>&1 | grep -B2 "Token Label:.*${LABEL}" | grep "^Slot " | head -1 | awk '{print $2}')
if [[ -z "${SLOT_ID}" ]]; then
  warn "Could not detect slot after init-token; defaulting to slot 0"
  SLOT_ID=0
fi
info "Token initialised at slot: ${SLOT_ID}"

# ---------------------------------------------------------------------------
# 5. Generate RSA-2048 key pair
# ---------------------------------------------------------------------------
info "Generating RSA-2048 key pair (label: test-signing-key, id: 01)..."
pkcs11-tool \
  --module "${LIB_PATH}" \
  --login --pin "${USER_PIN}" \
  --slot "${SLOT_ID}" \
  --keypairgen \
  --key-type rsa:2048 \
  --label "test-signing-key" \
  --id 01

# ---------------------------------------------------------------------------
# 6. Generate ECDSA P-256 key pair
# ---------------------------------------------------------------------------
info "Generating ECDSA P-256 key pair (label: test-ecdsa-key, id: 02)..."
pkcs11-tool \
  --module "${LIB_PATH}" \
  --login --pin "${USER_PIN}" \
  --slot "${SLOT_ID}" \
  --keypairgen \
  --key-type EC:prime256v1 \
  --label "test-ecdsa-key" \
  --id 02

# ---------------------------------------------------------------------------
# 7. List objects to confirm
# ---------------------------------------------------------------------------
info "Objects in token:"
pkcs11-tool \
  --module "${LIB_PATH}" \
  --login --pin "${USER_PIN}" \
  --slot "${SLOT_ID}" \
  --list-objects 2>&1 | sed 's/^/  /'

# ---------------------------------------------------------------------------
# 8. Print summary
# ---------------------------------------------------------------------------
cat <<SUMMARY

${GREEN}============================================================${NC}
${GREEN} HSM mock ready. Use these settings:${NC}
${GREEN}============================================================${NC}

  SOFTHSM2_CONF=${SOFTHSM2_CONF}
  (export this before running Elixir tests)

  IssuerKey hsm_config:
    library_path: ${LIB_PATH}
    slot_id:      ${SLOT_ID}
    pin:          ${USER_PIN}
    key_label:    test-signing-key   (RSA-2048)
               or test-ecdsa-key    (ECDSA P-256)

  For the Elixir test script:
    SOFTHSM2_CONF=${SOFTHSM2_CONF} \\
    SOFTHSM_LIB=${LIB_PATH} \\
    SOFTHSM_SLOT=${SLOT_ID} \\
    mix run scripts/test-hsm-flow.exs

  For Go agent config.yaml:
    pkcs11:
      library: ${LIB_PATH}
      slot:    ${SLOT_ID}
      pin:     "${USER_PIN}"

${GREEN}============================================================${NC}

SUMMARY
