import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :pki_ca_portal, PkiCaPortalWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Force using SSL in production. This also sets the "strict-security-transport" header,
# known as HSTS. If you have a health check endpoint, you may want to exclude it below.
# Note `:force_ssl` is required to be set at compile-time.
config :pki_ca_portal, PkiCaPortalWeb.Endpoint,
  force_ssl: [
    rewrite_on: [:x_forwarded_proto],
    exclude: [
      # paths: ["/health"],
      hosts: ["localhost", "127.0.0.1"]
    ]
  ]

# Signing salt — read at BUILD time (compile_env in endpoint.ex).
# Set CA_PORTAL_SIGNING_SALT in the build environment or source .env before mix release.
if salt = System.get_env("CA_PORTAL_SIGNING_SALT") do
  config :pki_ca_portal, signing_salt: salt
end

# Structured JSON logging for production — enables log aggregation
config :logger, :default_handler,
  formatter: {LoggerJSON.Formatters.Basic, metadata: :all}

config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
